mise en place des classname sur les label et input
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Origin pull request #13
Opened 2024-01-25 15:53 UTC by alain28190

2024-01-25 15:53 UTC, Zonzon58 submitted a review, later dismissed
ok

2024-01-26 08:47 UTC, aimach requested changes

2024-01-26 08:47 UTC, aimach commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +            <label className="lastname" type="text" name="text">
changer le nom de classe : par exemple "labelInscription"

2024-01-26 08:47 UTC, aimach commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +              <input className="nom" type="text" name="text" required />
changer le nom de classe : par exemple "inputInscription"

2024-01-26 09:36 UTC, aimach approved these changes

2024-01-26 09:39 UTC, Zonzon58 approved these changes
ok

2024-02-06 09:19 UTC, closed without merging

2024-02-06 09:20 UTC, alain28190 commented
ok pull re fait sur une autre pr .