mise en place du css page contact
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Origin pull request #15
Opened 2024-01-30 15:01 UTC by alain28190

2024-01-30 15:02 UTC, Zonzon58 submitted a review, later dismissed
OK

2024-01-30 15:44 UTC, aimach requested changes

2024-01-30 15:44 UTC, aimach commented on frontend/src/components/administration/AdminContact.css
>  @media only sreen and (max-width: 600px) {
enlever lignes 1 et 2

2024-01-30 15:44 UTC, aimach commented on frontend/src/components/administration/AdminContact.css
> +body {
déplacer dans App.css (importer App.css dans App.jsx)

2024-02-05 08:46 UTC, aimach approved these changes

2024-02-05 08:46 UTC, merged