Jmz authorisation mise en place brevo send.
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Origin pull request #16
Opened 2024-01-30 15:20 UTC by Zonzon58

2024-02-05 09:54 UTC, aimach requested changes

2024-02-05 09:54 UTC, aimach commented on frontend/src/pages/admin/LoginAdm.jsx
> +    //   const handleRequest = async (e) => {
enlever les commentaires

2024-02-05 09:54 UTC, aimach commented on frontend/src/pages/admin/Loginadm.css
supprimer ce fichier

2024-02-05 09:54 UTC, aimach commented on package-lock.json
ce fichier ne devrait pas être modifié, on regardera ça ensemble

2024-02-05 09:54 UTC, aimach commented on backend/database/schema.sql
> +create table client (
il faudrait ajouter un password si tu veux mettre en place le login ?

2024-02-05 09:54 UTC, aimach commented on frontend/src/pages/admin/LoginAdm.jsx
> +      console.log(valid);
enlever le console.log(valid) et mettre plutôt 
if (valide) setUser(valid)
le setUser venant du AuthContext

2024-02-06 09:08 UTC, closed without merging

2024-02-06 09:09 UTC, Zonzon58 commented on frontend/src/pages/admin/LoginAdm.jsx
> +      console.log(valid);
Le code à était écrasé par les mises à jour de la dernière merge et il n'est plus d'actualité.