création de la page indentification connexion
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Origin pull request #7
Opened 2024-01-10 14:48 UTC by alain28190

2024-01-10 14:49 UTC, Zonzon58 approved these changes
Bravo pour cette page d'inscription

2024-01-12 09:31 UTC, Zonzon58 submitted a review, later dismissed
ok

2024-01-12 10:16 UTC, Zonzon58 submitted a review, later dismissed
ok

2024-01-12 10:19 UTC, alain28190 commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +          <input type="nom" className="" />
corriger

2024-01-12 10:19 UTC, alain28190 commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +        <form className="nom">
corriger

2024-01-12 10:19 UTC, alain28190 commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +          <label htmlFor="nom">Nom</label>
corriger

2024-01-12 10:19 UTC, alain28190 commented on frontend/src/main.jsx
> +    loader: async () => {
fait

2024-01-12 10:20 UTC, alain28190 commented on frontend/src/main.jsx
> +    path: "/ InscriptOrigins",
corriger

2024-01-12 15:03 UTC, Zonzon58 approved these changes
pk

2024-01-15 10:55 UTC, jujuck requested changes

2024-01-15 10:55 UTC, jujuck commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +      <h1> InscriptOrigins </h1>
Ceci n'est pas un titre? Inscription sans espace autour

2024-01-15 10:55 UTC, jujuck commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +            prénom
Pourquoi prénom n'a pas de majuscule et les autres champs oui

2024-01-15 10:55 UTC, jujuck commented on frontend/src/pages/admin/InscriptOrigins.jsx
> +            Inscrption
Il manque un i à inscription

2024-01-15 10:59 UTC, Zonzon58 submitted a review, later dismissed
ok

2024-01-16 11:26 UTC, jujuck approved these changes

2024-01-16 11:26 UTC, merged