Jmz feat video contact
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Origin pull request #9
Opened 2024-01-22 15:42 UTC by Zonzon58

2024-01-22 15:43 UTC, alain28190 commented
ok

2024-01-22 15:44 UTC, alain28190 approved these changes
ok

2024-01-22 15:51 UTC, aimach requested changes

2024-01-22 15:51 UTC, aimach commented on frontend/src/components/administration/AdminContact.jsx
> +            @mail
email ou téléphone ? 
l'input est de type "phone" (ce qui n'existe pas, c'est "tel"). 
Si c'est un email, ce sera un input de type "email"

2024-01-23 13:31 UTC, Zonzon58 commented on frontend/src/components/administration/AdminContact.jsx
> +            @mail
rectifié par email

2024-01-23 14:36 UTC, aimach approved these changes

2024-01-23 14:38 UTC, alain28190 approved these changes
ok super

2024-01-23 14:38 UTC, merged